#!/usr/bin/env python
import rospy
from std_msgs.msg import String
global key
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %d", data.data) 
    key = data.data
    if key != " " :
        rospy.loginfo(Text)
    #if(value.data == 1)rospy.loginfo("oke ,%d",value.data)     
def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("button", String, callback)
    rospy.spin()
   
if __name__ == '__main__':
    listener()